/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vitorgreati.view.equipamentos;

import br.com.vitorgreati.model.Agendamento;
import br.com.vitorgreati.model.Equipamento;
import br.com.vitorgreati.model.SessaoUsuario;
import br.com.vitorgreati.persistence.AgendamentoDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vitor
 */
public class TelaReservarEquipamento extends javax.swing.JFrame {

    private AgendamentoDAO agendamentoDAO = null;
    private Equipamento equipamento = null;
    private ArrayList<Agendamento> agendamentos = null;
    
    private JFrame frameInvocador;
    /**
     * Creates new form TelaReservarEquipamento
     */
    public TelaReservarEquipamento(Equipamento equipamento, JFrame frameInvocador) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.equipamento = equipamento;
        this.agendamentoDAO = new AgendamentoDAO();
        
        this.frameInvocador = frameInvocador;
        
        setTitle("Reservar: "+equipamento.getNome());
        
        preencherTabela();
        
    }
    
    private void preencherTabela(){
        this.agendamentos = agendamentoDAO.listarPorEquipamento(this.equipamento);
        DefaultTableModel model = (DefaultTableModel) tbReservas.getModel();
        model.setRowCount(0);
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        for(Agendamento a : agendamentos){
            model.addRow(new String[]{format.format(a.getDataInicio()),format.format(a.getDataFinal()),a.getUsuario().getUsername()});
        }
        tbReservas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTudo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        snDe = new javax.swing.JSpinner();
        snAte = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        pnTabelaReservas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReservas = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservar equipamento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("De:");

        snDe.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        snDe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                snDeStateChanged(evt);
            }
        });
        snDe.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                snDeInputMethodTextChanged(evt);
            }
        });

        snAte.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        jLabel2.setText("Até:");

        pnTabelaReservas.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservas para este equipamento"));

        tbReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "De", "Até", "Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReservasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbReservas);

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTabelaReservasLayout = new javax.swing.GroupLayout(pnTabelaReservas);
        pnTabelaReservas.setLayout(pnTabelaReservasLayout);
        pnTabelaReservasLayout.setHorizontalGroup(
            pnTabelaReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTabelaReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTabelaReservasLayout.setVerticalGroup(
            pnTabelaReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTabelaReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTabelaReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExcluir)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Detalhes:");

        jButton2.setText("Reservar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTudoLayout = new javax.swing.GroupLayout(pnTudo);
        pnTudo.setLayout(pnTudoLayout);
        pnTudoLayout.setHorizontalGroup(
            pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTudoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(pnTudoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(snDe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snAte, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTudoLayout.createSequentialGroup()
                        .addGroup(pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(pnTabelaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnTudoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {snAte, snDe});

        pnTudoLayout.setVerticalGroup(
            pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(snDe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(snAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTudoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTudoLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTabelaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTudoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {snAte, snDe});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date dataInicio = (Date) snDe.getModel().getValue();
        Date dataFinal = (Date) snAte.getModel().getValue();
        String descricao = taDescricao.getText();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        if(format.format(dataInicio).equals(format.format(dataFinal))){
            JOptionPane.showMessageDialog(null, "As datas não podem ser iguais.", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }else{
            boolean agendamentoPermitido = true;
            for(Agendamento a : agendamentos){
                if((dataInicio.after(a.getDataInicio()) && dataInicio.before(a.getDataFinal())) || 
                        (dataFinal.after(a.getDataInicio()) && dataFinal.before(a.getDataFinal()))){
                    agendamentoPermitido = false;
                }
            }

            if(agendamentoPermitido){
                Agendamento agendamento = new Agendamento(descricao,dataInicio,dataFinal,SessaoUsuario.getUsuario(),this.equipamento);
                agendamentoDAO.cadastrar(agendamento);
                JOptionPane.showMessageDialog(null, "O equipamento foi agendado.", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                frameInvocador.setEnabled(true);
                dispose();
                //preencherTabela();
            }else{
                JOptionPane.showMessageDialog(null, "O equipamento já está agendado para esse período.", "Erro ao agendar", JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.frameInvocador.setEnabled(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void snDeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_snDeInputMethodTextChanged
                // TODO add your handling code here:
    }//GEN-LAST:event_snDeInputMethodTextChanged

    private void snDeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_snDeStateChanged
        snAte.setModel(new javax.swing.SpinnerDateModel((Date) snDe.getModel().getValue(), (Date) snDe.getModel().getValue(), null, java.util.Calendar.DAY_OF_MONTH));        // TODO add your handling code here:
    }//GEN-LAST:event_snDeStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.frameInvocador.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Agendamento agendamento = this.agendamentos.get(tbReservas.getSelectedRow());
        if(!agendamento.getUsuario().getUsername().equals(SessaoUsuario.getUsuario().getUsername())){
            JOptionPane.showMessageDialog(null, "Você só pode cancelar as suas reservas.", "Erro", JOptionPane.ERROR_MESSAGE);
        }else {
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja mesmo cancelar essa reserva?", "Confirmar exclusão", 
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(opcao==0){
                agendamentoDAO.excluir(agendamento);
                JOptionPane.showMessageDialog(null, "Agendamento cancelado.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.agendamentos.remove(tbReservas.getSelectedRow());
                DefaultTableModel model =(DefaultTableModel) tbReservas.getModel();
                model.removeRow(tbReservas.getSelectedRow());
            }        // TODO add your handling code here:
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tbReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReservasMouseClicked
        ativarDesativarBotoesPelaTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_tbReservasMouseClicked

    private void ativarDesativarBotoesPelaTabela(){
        if(tbReservas.getSelectedRow() != -1){
            btExcluir.setEnabled(true);
        }else{
            btExcluir.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReservarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReservarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReservarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReservarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReservarEquipamento(null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnTabelaReservas;
    private javax.swing.JPanel pnTudo;
    private javax.swing.JSpinner snAte;
    private javax.swing.JSpinner snDe;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTable tbReservas;
    // End of variables declaration//GEN-END:variables
}
