/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vitorgreati.view.equipamentos;

import br.com.vitorgreati.model.Autoridade;
import br.com.vitorgreati.model.SessaoUsuario;
import br.com.vitorgreati.model.Usuario;
import br.com.vitorgreati.persistence.UsuarioDAO;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vitor
 */
public class TelaBuscarUsuario extends javax.swing.JFrame {

    private UsuarioDAO usuarioDAO;
    
    private ArrayList<Usuario> usuarios;
    
    private JFrame frameInvocador;
    
    private String buscaNome;
    private ArrayList<String> autoridadesBusca;
    
    /**
     * Creates new form TelaBuscarUsuario
     */
    public TelaBuscarUsuario(JFrame frameInvocador) {
        initComponents();
        setLocationRelativeTo(null);
        
        usuarioDAO = new UsuarioDAO();
        
        this.frameInvocador = frameInvocador;
        
        if(SessaoUsuario.getUsuario() == null){
            btAtualizar.setVisible(false);
            btExcluir.setVisible(false);
        }else{
            ArrayList<String> autoridades = new ArrayList<>();
            for(Autoridade autoridade : SessaoUsuario.getUsuario().getAutoridades()){
                autoridades.add(autoridade.getNome());
            }

            // mudar view de acordo com o usuário
            if(!autoridades.contains("Administrador")){
                btAtualizar.setVisible(false);
                btExcluir.setVisible(false);
            }
            if(!autoridades.contains("Estudante")){
                
            }
            if(!autoridades.contains("Orientador")){

            }
        }
        
        this.usuarios = usuarioDAO.listar();
        DefaultTableModel model = (DefaultTableModel) tbUsuarios.getModel();
        model.setRowCount(0);
        for(Usuario u : usuarios){
            model.addRow(new String[]{u.getUsername(),u.getNome(),new SimpleDateFormat("dd/MM/yyyy").format(u.getDataCadastro())});
        }

    }

    public TelaBuscarUsuario(String busca, JFrame frameInvocador) {
        initComponents();
        setLocationRelativeTo(null);
        
        usuarioDAO = new UsuarioDAO();
                
        this.frameInvocador = frameInvocador;
        
        usuarios = usuarioDAO.buscarOtimizado(busca, "", "", null);
        
        tfNome.setText(busca);
        
        DefaultTableModel model = (DefaultTableModel) tbUsuarios.getModel();
        model.setRowCount(0);
        for(Usuario u : usuarios){
            model.addRow(new String[]{u.getUsername(),u.getNome(),new SimpleDateFormat("dd/MM/yyyy").format(u.getDataCadastro())});
        }
        
        if(SessaoUsuario.getUsuario() == null){
            btAtualizar.setVisible(false);
            btExcluir.setVisible(false);
        }else{
            ArrayList<String> autoridades = new ArrayList<>();
            for(Autoridade autoridade : SessaoUsuario.getUsuario().getAutoridades()){
                autoridades.add(autoridade.getNome());
            }

            // mudar view de acordo com o usuário
            if(!autoridades.contains("Administrador")){
                btAtualizar.setVisible(false);
                btExcluir.setVisible(false);
            }
            if(!autoridades.contains("Estudante")){
                
            }
            if(!autoridades.contains("Orientador")){

            }
        }
    }
    
    public void preencherDepoisDeAtualizar(Usuario u){
        DefaultTableModel model = (DefaultTableModel) tbUsuarios.getModel();
        model.setRowCount(0);
        model.addRow(new String[]{u.getUsername(),u.getNome(),new SimpleDateFormat("dd/MM/yyyy").format(u.getDataCadastro())});   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTudo = new javax.swing.JPanel();
        pnBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEstados = new javax.swing.JComboBox();
        pnAutoridades = new javax.swing.JPanel();
        cbAdministrador = new javax.swing.JCheckBox();
        cbOrientador = new javax.swing.JCheckBox();
        cbEstudante = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        cbEstado = new javax.swing.JCheckBox();
        pnUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        btDetalhes = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Username:");

        jLabel3.setText("Estado:");

        cbEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstados.setEnabled(false);

        cbAdministrador.setText("Administrador");

        cbOrientador.setText("Orientador");

        cbEstudante.setText("Estudante");

        jLabel4.setText("Autoridades:");

        javax.swing.GroupLayout pnAutoridadesLayout = new javax.swing.GroupLayout(pnAutoridades);
        pnAutoridades.setLayout(pnAutoridadesLayout);
        pnAutoridadesLayout.setHorizontalGroup(
            pnAutoridadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAutoridadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEstudante)
                .addContainerGap())
        );
        pnAutoridadesLayout.setVerticalGroup(
            pnAutoridadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAutoridadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbAdministrador)
                .addComponent(jLabel4))
            .addComponent(cbOrientador)
            .addComponent(cbEstudante)
        );

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarLayout = new javax.swing.GroupLayout(pnBuscar);
        pnBuscar.setLayout(pnBuscarLayout);
        pnBuscarLayout.setHorizontalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnAutoridades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarLayout.createSequentialGroup()
                                .addComponent(btBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpar)
                                .addGap(21, 21, 21))))))
        );
        pnBuscarLayout.setVerticalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarLayout.createSequentialGroup()
                        .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addComponent(pnAutoridades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btBuscar))
                .addContainerGap())
        );

        pnUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários encontrados"));

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuário", "Nome", "Desde"
            }
        ));
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuarios);

        btDetalhes.setText("Detalhes");
        btDetalhes.setEnabled(false);
        btDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalhesActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnUsuariosLayout = new javax.swing.GroupLayout(pnUsuarios);
        pnUsuarios.setLayout(pnUsuariosLayout);
        pnUsuariosLayout.setHorizontalGroup(
            pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuariosLayout.createSequentialGroup()
                .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnUsuariosLayout.setVerticalGroup(
            pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addComponent(btDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnTudoLayout = new javax.swing.GroupLayout(pnTudo);
        pnTudo.setLayout(pnTudoLayout);
        pnTudoLayout.setHorizontalGroup(
            pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTudoLayout.setVerticalGroup(
            pnTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String nome = tfNome.getText();
        String username = tfUsername.getText();
        String estado = cbEstados.isEnabled() ? cbEstados.getSelectedItem().toString() : "";
        
        ArrayList<String> autoridades = new ArrayList<>();
        for(Component c : pnAutoridades.getComponents()){
            if(c instanceof JCheckBox){
                if(((JCheckBox)c).isSelected())
                    autoridades.add(((JCheckBox)c).getText());
            }
        }
        
        usuarios = usuarioDAO.buscarOtimizado(nome, username, estado, autoridades);
        
        
        DefaultTableModel model = (DefaultTableModel) tbUsuarios.getModel();
        model.setRowCount(0);
        for(Usuario u : usuarios){
            try{
                model.addRow(new String[]{u.getUsername(),u.getNome(),new SimpleDateFormat("dd/MM/yyyy").format(u.getDataCadastro())});
            }catch(NullPointerException e){}
        }
        if(model.getRowCount()==0) ativarDesativarBotoesPelaTabela();

        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        if(cbEstado.isSelected()){
            cbEstados.setEnabled(true);
        }else{
            cbEstados.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalhesActionPerformed
        new TelaDetalhesUsuario(usuarios.get(tbUsuarios.getSelectedRow()),this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btDetalhesActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        new TelaEditarUsuario(usuarios.get(tbUsuarios.getSelectedRow()),this).setVisible(true);
        setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Usuario usuarioSelecionado = usuarios.get(tbUsuarios.getSelectedRow());
        
        if(usuarioSelecionado.getId()==SessaoUsuario.getUsuario().getId()){
            System.out.println(usuarioSelecionado.getId());
            System.out.println(SessaoUsuario.getUsuario().getId());
            JOptionPane.showMessageDialog(null, "Você não pode se excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
        }else if(usuarioSelecionado.getId()==1){
            JOptionPane.showMessageDialog(null, "O administrador primário não pode ser excluído.", "Erro", JOptionPane.ERROR_MESSAGE);
        }else {
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir "+usuarioSelecionado.getNome()+" do sistema?", "Confirmar exclusão", 
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(opcao==0){
                AvatarTools.excluirAvatar(AvatarTools.AVATAR_USUARIO, usuarioSelecionado.getId());
                usuarioDAO.excluir(usuarioSelecionado);
                JOptionPane.showMessageDialog(null, "O usuário foi excluído.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel model =(DefaultTableModel) tbUsuarios.getModel();
                model.removeRow(tbUsuarios.getSelectedRow());
                
            }        // TODO add your handling code here:
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.frameInvocador.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.frameInvocador.setEnabled(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfNome.setText("");
        tfUsername.setText("");
        cbEstados.setSelectedIndex(0);
        cbEstado.setSelected(false);
        for(Component c : pnAutoridades.getComponents()){
            if(c instanceof JCheckBox){
                ((JCheckBox)c).setSelected(false);
            }
        }
        cbEstados.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        ativarDesativarBotoesPelaTabela();
// TODO add your handling code here:
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void ativarDesativarBotoesPelaTabela(){
        if(tbUsuarios.getSelectedRow() != -1){                   
            btDetalhes.setEnabled(true);
            btAtualizar.setEnabled(true);
            btExcluir.setEnabled(true);
        }else{
            btDetalhes.setEnabled(false);
            btAtualizar.setEnabled(false);
            btExcluir.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscarUsuario(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btDetalhes;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JCheckBox cbAdministrador;
    private javax.swing.JCheckBox cbEstado;
    private javax.swing.JComboBox cbEstados;
    private javax.swing.JCheckBox cbEstudante;
    private javax.swing.JCheckBox cbOrientador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAutoridades;
    private javax.swing.JPanel pnBuscar;
    private javax.swing.JPanel pnTudo;
    private javax.swing.JPanel pnUsuarios;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
