/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vitorgreati.view.equipamentos;

import br.com.vitorgreati.model.Autoridade;
import br.com.vitorgreati.model.SessaoUsuario;
import br.com.vitorgreati.model.Usuario;
import br.com.vitorgreati.persistence.ProjetoDAO;
import br.com.vitorgreati.persistence.UsuarioDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class TelaInicialLogada extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    private UsuarioDAO usuarioDAO;
    private ProjetoDAO projetoDAO;
    
    public TelaInicialLogada() {
        initComponents();
        setLocationRelativeTo(null);
        usuarioDAO = new UsuarioDAO();
        projetoDAO = new ProjetoDAO();
        
        
        ArrayList<String> autoridades = new ArrayList<>();
        for(Autoridade autoridade : SessaoUsuario.getUsuario().getAutoridades()){
            autoridades.add(autoridade.getNome());
        }
        
        // mudar view de acordo com o usuário
        if(!autoridades.contains("Administrador")){
            miCadastrarEquip.setVisible(false);
            miAtualizarEquip.setVisible(false);
            miExcluirEquip.setVisible(false);
            
            miCadastrarUsu.setVisible(false);
            miAtualizarUsu.setVisible(false);
            miExcluirUsu.setVisible(false);
            
            miExcluirProj.setVisible(false);
            miNovoProj.setVisible(false);
            miAtualizarProj.setVisible(false);
            
            lbAdmin.setVisible(false);
        }
        if(!autoridades.contains("Estudante")){
            miReservarEquip.setVisible(false);
            lbEstudante.setVisible(false);
        }
        if(!autoridades.contains("Orientador")){
            lbOrientador.setVisible(false);
        }
        
        lbProjetos.setText(String.valueOf(SessaoUsuario.getUsuario().getProjetos().size()));
        
        //carregando imagem
        try{
            ImageIcon foto = new ImageIcon(AvatarTools.getAvatar(AvatarTools.AVATAR_USUARIO, SessaoUsuario.getUsuario().getId(),lbFoto.getWidth(), lbFoto.getHeight()));
            lbFoto.setIcon(foto);
        }catch(IOException ioe){}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltroBusca = new javax.swing.ButtonGroup();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        pnAutenticar = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbProjetos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbAdmin = new javax.swing.JLabel();
        lbOrientador = new javax.swing.JLabel();
        lbEstudante = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        pnBuscarReagente = new javax.swing.JPanel();
        tfBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        rbEquipamento = new javax.swing.JRadioButton();
        rbUsuario = new javax.swing.JRadioButton();
        rbProjeto = new javax.swing.JRadioButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbInstituicao = new javax.swing.JLabel();
        lbLocalizacao = new javax.swing.JLabel();
        lbDesde = new javax.swing.JLabel();
        lbDesde1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsultarEquip = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        miCadastrarEquip = new javax.swing.JMenuItem();
        miAtualizarEquip = new javax.swing.JMenuItem();
        miExcluirEquip = new javax.swing.JMenuItem();
        miReservarEquip = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miConsultarUsu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miCadastrarUsu = new javax.swing.JMenuItem();
        miAtualizarUsu = new javax.swing.JMenuItem();
        miExcluirUsu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miConsultar = new javax.swing.JMenuItem();
        miProjetosProj = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        miNovoProj = new javax.swing.JMenuItem();
        miAtualizarProj = new javax.swing.JMenuItem();
        miExcluirProj = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("God4Labs - Gerenciador de Laboratórios de Química");

        pnAutenticar.setBorder(javax.swing.BorderFactory.createTitledBorder("Bem-vindo, "+SessaoUsuario.getUsuario().getUsername()));
        pnAutenticar.setMinimumSize(new java.awt.Dimension(247, 168));

        lbFoto.setBackground(new java.awt.Color(255, 255, 255));
        lbFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Projetos:");

        lbProjetos.setText("0");

        jLabel13.setText("Autoridades:");

        lbAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lbAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/aut_admin_ativo.png"))); // NOI18N
        lbAdmin.setToolTipText("Administrador");

        lbOrientador.setBackground(new java.awt.Color(255, 255, 255));
        lbOrientador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/aut_orientador_ativo.png"))); // NOI18N
        lbOrientador.setToolTipText("Orientador");

        lbEstudante.setBackground(new java.awt.Color(255, 255, 255));
        lbEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/aut_pesquisador_ativo.png"))); // NOI18N
        lbEstudante.setToolTipText("Pesquisador");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("Editar perfil...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setText("Ver perfil");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel14.setText("Nome:");

        lbNome.setText(SessaoUsuario.getUsuario().getNome());

        javax.swing.GroupLayout pnAutenticarLayout = new javax.swing.GroupLayout(pnAutenticar);
        pnAutenticar.setLayout(pnAutenticarLayout);
        pnAutenticarLayout.setHorizontalGroup(
            pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAutenticarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAutenticarLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(pnAutenticarLayout.createSequentialGroup()
                        .addComponent(lbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnAutenticarLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnAutenticarLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbNome))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAutenticarLayout.setVerticalGroup(
            pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAutenticarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAutenticarLayout.createSequentialGroup()
                        .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lbNome))
                        .addGap(11, 11, 11)
                        .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lbProjetos))
                        .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnAutenticarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnAutenticarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lbEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnAutenticarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnBuscarReagente.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca rápida"));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        bgFiltroBusca.add(rbEquipamento);
        rbEquipamento.setText("Equipamento");

        bgFiltroBusca.add(rbUsuario);
        rbUsuario.setText("Usuário");

        bgFiltroBusca.add(rbProjeto);
        rbProjeto.setText("Projeto");

        javax.swing.GroupLayout pnBuscarReagenteLayout = new javax.swing.GroupLayout(pnBuscarReagente);
        pnBuscarReagente.setLayout(pnBuscarReagenteLayout);
        pnBuscarReagenteLayout.setHorizontalGroup(
            pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarReagenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarReagenteLayout.createSequentialGroup()
                        .addComponent(rbEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbProjeto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarReagenteLayout.createSequentialGroup()
                        .addComponent(tfBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnBuscarReagenteLayout.setVerticalGroup(
            pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarReagenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBuscar)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEquipamento)
                    .addComponent(rbUsuario)
                    .addComponent(rbProjeto))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/search_equip_menor.png"))); // NOI18N
        jButton2.setToolTipText("Procurar equipamento");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/search_usu_menor.png"))); // NOI18N
        jButton3.setToolTipText("Encontrar usuário");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/search_proj_menor.png"))); // NOI18N
        jButton4.setToolTipText("Procurar projeto");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações gerais do laboratório"));

        jLabel1.setText("Instituição:");

        jLabel2.setText("Localização:");

        jLabel3.setText("Desde:");

        jLabel4.setText("Descrição:");

        lbInstituicao.setForeground(new java.awt.Color(153, 153, 153));
        lbInstituicao.setText("Instituto Federal do Rio Grande do Norte Campus Natal Zona-Norte");

        lbLocalizacao.setForeground(new java.awt.Color(153, 153, 153));
        lbLocalizacao.setText("Natal/RN");

        lbDesde.setForeground(new java.awt.Color(153, 153, 153));
        lbDesde.setText("2009");

        lbDesde1.setForeground(new java.awt.Color(153, 153, 153));
        lbDesde1.setText("Laboratório de Química e Biologia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDesde1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbInstituicao))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbLocalizacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbDesde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbDesde1))
                .addGap(8, 8, 8))
        );

        mnArquivo.setText("Arquivo");

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miSair);

        jMenuBar1.add(mnArquivo);

        jMenu2.setText("Equipamentos");

        miConsultarEquip.setText("Consultar...");
        miConsultarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarEquipActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultarEquip);
        jMenu2.add(jSeparator3);

        miCadastrarEquip.setText("Novo...");
        miCadastrarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarEquipActionPerformed(evt);
            }
        });
        jMenu2.add(miCadastrarEquip);

        miAtualizarEquip.setText("Atualizar...");
        miAtualizarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtualizarEquipActionPerformed(evt);
            }
        });
        jMenu2.add(miAtualizarEquip);

        miExcluirEquip.setText("Excluir... ");
        miExcluirEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirEquipActionPerformed(evt);
            }
        });
        jMenu2.add(miExcluirEquip);

        miReservarEquip.setText("Reservar...");
        miReservarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReservarEquipActionPerformed(evt);
            }
        });
        jMenu2.add(miReservarEquip);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Usuários");

        miConsultarUsu.setText("Consultar...");
        miConsultarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarUsuActionPerformed(evt);
            }
        });
        jMenu3.add(miConsultarUsu);
        jMenu3.add(jSeparator2);

        miCadastrarUsu.setText("Novo...");
        miCadastrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarUsuActionPerformed(evt);
            }
        });
        jMenu3.add(miCadastrarUsu);

        miAtualizarUsu.setText("Atualizar...");
        miAtualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtualizarUsuActionPerformed(evt);
            }
        });
        jMenu3.add(miAtualizarUsu);

        miExcluirUsu.setText("Excluir...");
        miExcluirUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirUsuActionPerformed(evt);
            }
        });
        jMenu3.add(miExcluirUsu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Projetos");

        miConsultar.setText("Consultar...");
        miConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarActionPerformed(evt);
            }
        });
        jMenu4.add(miConsultar);

        miProjetosProj.setText("Meus projetos");
        miProjetosProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProjetosProjActionPerformed(evt);
            }
        });
        jMenu4.add(miProjetosProj);
        jMenu4.add(jSeparator4);

        miNovoProj.setText("Novo...");
        miNovoProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoProjActionPerformed(evt);
            }
        });
        jMenu4.add(miNovoProj);

        miAtualizarProj.setText("Atualizar...");
        miAtualizarProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtualizarProjActionPerformed(evt);
            }
        });
        jMenu4.add(miAtualizarProj);

        miExcluirProj.setText("Excluir...");
        miExcluirProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirProjActionPerformed(evt);
            }
        });
        jMenu4.add(miExcluirProj);

        jMenuBar1.add(jMenu4);

        mnAjuda.setText("Ajuda");

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnAjuda.add(jMenuItem5);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnBuscarReagente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBuscarReagente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnAutenticar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastrarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarEquipActionPerformed
        new TelaEditorEquipamento(null,this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadastrarEquipActionPerformed

    private void miExcluirEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirEquipActionPerformed
        new TelaSelecionarEquipamento(TelaSelecionarEquipamento.EXCLUIR,this).setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_miExcluirEquipActionPerformed

    private void miAtualizarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtualizarEquipActionPerformed
        new TelaSelecionarEquipamento(TelaSelecionarEquipamento.ATUALIZAR,this).setVisible(true);
        setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_miAtualizarEquipActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, SessaoUsuario.getUsuario().getNome().split(" ")[0]+", deseja mesmo sair?", "Confirmar logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opcao==0){
            SessaoUsuario.setUsuario(null);
            dispose();
            new TelaInicial().setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void miCadastrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarUsuActionPerformed
        new TelaNovoUsuario(this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadastrarUsuActionPerformed

    private void miConsultarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarUsuActionPerformed
        new TelaBuscarUsuario(this).setVisible(true);        
        setEnabled(false);
    }//GEN-LAST:event_miConsultarUsuActionPerformed

    private void miConsultarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarEquipActionPerformed
        new TelaBuscarEquipamento(this).setVisible(true);         
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miConsultarEquipActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new TelaEditarUsuario(SessaoUsuario.getUsuario(),this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void miAtualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtualizarUsuActionPerformed
        new TelaSelecionarUsuario(TelaSelecionarUsuario.ATUALIZAR,this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miAtualizarUsuActionPerformed

    private void miExcluirUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirUsuActionPerformed
        new TelaSelecionarUsuario(TelaSelecionarUsuario.EXCLUIR,this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miExcluirUsuActionPerformed

    private void miReservarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReservarEquipActionPerformed
        new TelaSelecionarEquipamento(TelaSelecionarEquipamento.RESERVAR,this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miReservarEquipActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new TelaDetalhesUsuario(SessaoUsuario.getUsuario(),this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void miNovoProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoProjActionPerformed
        new TelaEditorProjeto(null,this).setVisible(true);        
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miNovoProjActionPerformed

    private void miProjetosProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProjetosProjActionPerformed
        Usuario usuario = usuarioDAO.buscarPorId(SessaoUsuario.getUsuario().getId());
        usuario.setProjetos(projetoDAO.buscarProjetosPorUsuario(usuario));
        new TelaMeusProjetos(usuario,this).setVisible(true);   
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miProjetosProjActionPerformed

    private void miAtualizarProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtualizarProjActionPerformed
        new TelaSelecionarProjeto(TelaSelecionarProjeto.ATUALIZAR,this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miAtualizarProjActionPerformed

    private void miExcluirProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirProjActionPerformed
        new TelaSelecionarProjeto(TelaSelecionarProjeto.EXCLUIR,this).setVisible(true);
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_miExcluirProjActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_miSairActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new TelaSobre(this).setVisible(true);
        setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String  busca = tfBuscar.getText();
        if(!busca.trim().equals("")){
            if(rbEquipamento.isSelected()){
                new TelaBuscarEquipamento(busca,this).setVisible(true);
                setEnabled(false);
            }else if(rbUsuario.isSelected()){
                new TelaBuscarUsuario(busca,this).setVisible(true);
                setEnabled(false);
            }else if(rbProjeto.isSelected()){
                new TelaSelecionarProjeto(busca,TelaSelecionarProjeto.CONSULTA,this).setVisible(true);
                setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Escolha uma opção de busca.","Atenção",JOptionPane.WARNING_MESSAGE);
                rbEquipamento.requestFocus();
            }
        }else{
                JOptionPane.showMessageDialog(null, "Digite algo na caixa de busca.","Atenção",JOptionPane.WARNING_MESSAGE);
                tfBuscar.requestFocus();        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed

    private void miConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarActionPerformed
        new TelaSelecionarProjeto(TelaSelecionarProjeto.CONSULTA,this).setVisible(true);
        setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_miConsultarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new TelaBuscarEquipamento(this).setVisible(true);        
        setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new TelaBuscarUsuario(this).setVisible(true);        
        setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaSelecionarProjeto(TelaSelecionarProjeto.CONSULTA,this).setVisible(true);
        setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialLogada().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltroBusca;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbDesde;
    private javax.swing.JLabel lbDesde1;
    private javax.swing.JLabel lbEstudante;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbInstituicao;
    private javax.swing.JLabel lbLocalizacao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JLabel lbProjetos;
    private javax.swing.JMenuItem miAtualizarEquip;
    private javax.swing.JMenuItem miAtualizarProj;
    private javax.swing.JMenuItem miAtualizarUsu;
    private javax.swing.JMenuItem miCadastrarEquip;
    private javax.swing.JMenuItem miCadastrarUsu;
    private javax.swing.JMenuItem miConsultar;
    private javax.swing.JMenuItem miConsultarEquip;
    private javax.swing.JMenuItem miConsultarUsu;
    private javax.swing.JMenuItem miExcluirEquip;
    private javax.swing.JMenuItem miExcluirProj;
    private javax.swing.JMenuItem miExcluirUsu;
    private javax.swing.JMenuItem miNovoProj;
    private javax.swing.JMenuItem miProjetosProj;
    private javax.swing.JMenuItem miReservarEquip;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JPanel pnAutenticar;
    private javax.swing.JPanel pnBuscarReagente;
    private javax.swing.JRadioButton rbEquipamento;
    private javax.swing.JRadioButton rbProjeto;
    private javax.swing.JRadioButton rbUsuario;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables
}
