/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vitorgreati.view.equipamentos;

import br.com.vitorgreati.model.SessaoUsuario;
import br.com.vitorgreati.model.Usuario;
import br.com.vitorgreati.persistence.UsuarioDAO;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Vitor
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    private UsuarioDAO usuarioDAO;
    
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        usuarioDAO = new UsuarioDAO();
        
        if(SessaoUsuario.getUsuario() != null){
            quandoLogar();
        }
        
        mnProjetos.setVisible(false);
        mnReagentes.setVisible(false);
        mnEquipamentos.setVisible(false);
        mnUsuarios.setVisible(false);
       
    }
    
    private void quandoLogar(){
        for(Component c : pnAutenticar.getComponents()){
            if(c instanceof JButton || c instanceof JTextField || c instanceof JLabel){
                c.setVisible(false);
            }
        }
        
        pnAutenticar.setBorder(BorderFactory.createTitledBorder("Bem-vindo, "+SessaoUsuario.getUsuario().getUsername()));
        
        JLabel labelFoto = new JLabel();
        labelFoto.setBounds(0, 0, 80, 90);
        labelFoto.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        labelFoto.setLocation(10, 20);
        pnAutenticar.add(labelFoto);
        
        JLabel lbDesde = new JLabel();
        lbDesde.setText("Desde:");
        lbDesde.setBounds(0, 0, 100, 20);
        lbDesde.setLocation(110, 20);
        pnAutenticar.add(lbDesde);
        
        JLabel lbDesdeData = new JLabel();
        lbDesdeData.setText(new SimpleDateFormat("dd/MM/yyyy").format(SessaoUsuario.getUsuario().getDataCadastro()));
        lbDesdeData.setBounds(0, 0, 100, 20);
        lbDesdeData.setLocation(110, 30);
        pnAutenticar.add(lbDesdeData);
        
        JLabel lbAutoridadesTitulo = new JLabel();
        lbAutoridadesTitulo.setText("Autoridades:");
        lbAutoridadesTitulo.setBounds(0,0,100,20);
        lbAutoridadesTitulo.setLocation(110, 40);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltroBusca = new javax.swing.ButtonGroup();
        pnAutenticar = new javax.swing.JPanel();
        lbSenha = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JButton();
        btSolicitarCadastro = new javax.swing.JButton();
        pnBuscarReagente = new javax.swing.JPanel();
        tfBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        rbEquipamento = new javax.swing.JRadioButton();
        rbUsuario = new javax.swing.JRadioButton();
        rbProjeto = new javax.swing.JRadioButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbInstituicao = new javax.swing.JLabel();
        lbLocalizacao = new javax.swing.JLabel();
        lbDesde = new javax.swing.JLabel();
        lbDesde1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnReagentes = new javax.swing.JMenu();
        mnEquipamentos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenu();
        mnProjetos = new javax.swing.JMenu();
        mnAjuda = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("God4Labs - Gerenciador de Laboratórios de Química");

        pnAutenticar.setBorder(javax.swing.BorderFactory.createTitledBorder("É cadastrado?"));
        pnAutenticar.setMinimumSize(new java.awt.Dimension(247, 168));

        lbSenha.setText("Senha");

        lbUsuario.setText("Usuário");

        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btSolicitarCadastro.setText("Solicitar cadastro");
        btSolicitarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolicitarCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAutenticarLayout = new javax.swing.GroupLayout(pnAutenticar);
        pnAutenticar.setLayout(pnAutenticarLayout);
        pnAutenticarLayout.setHorizontalGroup(
            pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAutenticarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAutenticarLayout.createSequentialGroup()
                        .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfSenha)))
                    .addGroup(pnAutenticarLayout.createSequentialGroup()
                        .addComponent(btEntrar)
                        .addGap(10, 10, 10)
                        .addComponent(btSolicitarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnAutenticarLayout.setVerticalGroup(
            pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAutenticarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAutenticarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSolicitarCadastro))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnAutenticarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEntrar, btSolicitarCadastro});

        pnBuscarReagente.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca rápida"));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        bgFiltroBusca.add(rbEquipamento);
        rbEquipamento.setText("Equipamento");

        bgFiltroBusca.add(rbUsuario);
        rbUsuario.setText("Usuário");

        bgFiltroBusca.add(rbProjeto);
        rbProjeto.setText("Projeto");

        javax.swing.GroupLayout pnBuscarReagenteLayout = new javax.swing.GroupLayout(pnBuscarReagente);
        pnBuscarReagente.setLayout(pnBuscarReagenteLayout);
        pnBuscarReagenteLayout.setHorizontalGroup(
            pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarReagenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarReagenteLayout.createSequentialGroup()
                        .addComponent(rbEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbProjeto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarReagenteLayout.createSequentialGroup()
                        .addComponent(tfBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnBuscarReagenteLayout.setVerticalGroup(
            pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarReagenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBuscar)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuscarReagenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEquipamento)
                    .addComponent(rbUsuario)
                    .addComponent(rbProjeto))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/search_equip_menor.png"))); // NOI18N
        jButton2.setToolTipText("Procurar equipamento");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/search_usu_menor.png"))); // NOI18N
        jButton3.setToolTipText("Encontrar usuário");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vitorgreati/images/search_proj_menor.png"))); // NOI18N
        jButton4.setToolTipText("Procurar projeto");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações gerais do laboratório"));

        jLabel1.setText("Instituição:");

        jLabel2.setText("Localização:");

        jLabel3.setText("Desde:");

        jLabel4.setText("Descrição:");

        lbInstituicao.setForeground(new java.awt.Color(153, 153, 153));
        lbInstituicao.setText("Instituto Federal do Rio Grande do Norte Campus Natal Zona-Norte");

        lbLocalizacao.setForeground(new java.awt.Color(153, 153, 153));
        lbLocalizacao.setText("Natal/RN");

        lbDesde.setForeground(new java.awt.Color(153, 153, 153));
        lbDesde.setText("2009");

        lbDesde1.setForeground(new java.awt.Color(153, 153, 153));
        lbDesde1.setText("Laboratório de Química e Biologia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDesde1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbInstituicao))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbLocalizacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbDesde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbDesde1))
                .addGap(8, 8, 8))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        mnArquivo.setText("Arquivo");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnArquivo.add(jMenuItem7);

        jMenuBar1.add(mnArquivo);

        mnReagentes.setText("Reagentes");
        jMenuBar1.add(mnReagentes);

        mnEquipamentos.setText("Equipamentos");

        jMenuItem1.setText("Consultar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnEquipamentos.add(jMenuItem1);
        mnEquipamentos.add(jSeparator1);

        jMenuItem3.setText("Cadastrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnEquipamentos.add(jMenuItem3);

        jMenuItem4.setText("Atualizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnEquipamentos.add(jMenuItem4);

        jMenuItem5.setText("Excluir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnEquipamentos.add(jMenuItem5);

        jMenuItem2.setText("Reservar");
        mnEquipamentos.add(jMenuItem2);

        jMenuBar1.add(mnEquipamentos);

        mnUsuarios.setText("Usuários");
        jMenuBar1.add(mnUsuarios);

        mnProjetos.setText("Projetos");
        jMenuBar1.add(mnProjetos);

        mnAjuda.setText("Ajuda");

        jMenuItem6.setText("Sobre");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnAjuda.add(jMenuItem6);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnAutenticar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnBuscarReagente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnAutenticar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBuscarReagente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        String username = tfUsuario.getText();
        String senha = String.valueOf(pfSenha.getPassword());
        
        Usuario usuario = usuarioDAO.logar(username,senha);
        
        if(usuario==null){
            JOptionPane.showMessageDialog(null, "Dados de acesso incorretos.", "Erro ao logar", JOptionPane.ERROR_MESSAGE);
        }else{
            SessaoUsuario.setUsuario(usuario);
            dispose();
            new TelaInicialLogada().setVisible(true);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btEntrarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new TelaEditorEquipamento(null,this).setVisible(true);        
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new TelaSelecionarEquipamento(TelaSelecionarEquipamento.EXCLUIR,this).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new TelaSelecionarEquipamento(TelaSelecionarEquipamento.ATUALIZAR,this).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new TelaBuscarEquipamento(this).setVisible(true);  
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new TelaBuscarEquipamento(this).setVisible(true);        
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new TelaBuscarUsuario(this).setVisible(true);        
        setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new TelaSobre(this).setVisible(true);
        setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String  busca = tfBuscar.getText();
        if(!busca.trim().equals("")){
            if(rbEquipamento.isSelected()){
                new TelaBuscarEquipamento(busca,this).setVisible(true);
                setEnabled(false);
            }else if(rbUsuario.isSelected()){
                new TelaBuscarUsuario(busca,this).setVisible(true);
                setEnabled(false);
            }else if(rbProjeto.isSelected()){
                new TelaSelecionarProjeto(busca,TelaSelecionarProjeto.CONSULTA,this).setVisible(true);
                setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Escolha uma opção de busca.","Atenção",JOptionPane.WARNING_MESSAGE);
                rbEquipamento.requestFocus();
            }
        }else{
                JOptionPane.showMessageDialog(null, "Digite algo na caixa de busca.","Atenção",JOptionPane.WARNING_MESSAGE);
                tfBuscar.requestFocus();        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaSelecionarProjeto(TelaSelecionarProjeto.CONSULTA,this).setVisible(true);
        setEnabled(false);                // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btSolicitarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolicitarCadastroActionPerformed
        JOptionPane.showMessageDialog(null, "Encontre um administrador com a barra de busca rápida e entre em contato.");        // TODO add your handling code here:
    }//GEN-LAST:event_btSolicitarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltroBusca;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btSolicitarCadastro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbDesde;
    private javax.swing.JLabel lbDesde1;
    private javax.swing.JLabel lbInstituicao;
    private javax.swing.JLabel lbLocalizacao;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnEquipamentos;
    private javax.swing.JMenu mnProjetos;
    private javax.swing.JMenu mnReagentes;
    private javax.swing.JMenu mnUsuarios;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPanel pnAutenticar;
    private javax.swing.JPanel pnBuscarReagente;
    private javax.swing.JRadioButton rbEquipamento;
    private javax.swing.JRadioButton rbProjeto;
    private javax.swing.JRadioButton rbUsuario;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
